//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThoughtWorks.QRCode.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ThoughtWorks.QRCode.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] qrv1_0 {
            get {
                object obj = ResourceManager.GetObject("qrv1_0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv1_1 {
            get {
                object obj = ResourceManager.GetObject("qrv1_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv1_2 {
            get {
                object obj = ResourceManager.GetObject("qrv1_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv1_3 {
            get {
                object obj = ResourceManager.GetObject("qrv1_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv10_0 {
            get {
                object obj = ResourceManager.GetObject("qrv10_0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv10_1 {
            get {
                object obj = ResourceManager.GetObject("qrv10_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv10_2 {
            get {
                object obj = ResourceManager.GetObject("qrv10_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv10_3 {
            get {
                object obj = ResourceManager.GetObject("qrv10_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv11_0 {
            get {
                object obj = ResourceManager.GetObject("qrv11_0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv11_1 {
            get {
                object obj = ResourceManager.GetObject("qrv11_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv11_2 {
            get {
                object obj = ResourceManager.GetObject("qrv11_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv11_3 {
            get {
                object obj = ResourceManager.GetObject("qrv11_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv12_0 {
            get {
                object obj = ResourceManager.GetObject("qrv12_0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv12_1 {
            get {
                object obj = ResourceManager.GetObject("qrv12_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv12_2 {
            get {
                object obj = ResourceManager.GetObject("qrv12_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv12_3 {
            get {
                object obj = ResourceManager.GetObject("qrv12_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv13_0 {
            get {
                object obj = ResourceManager.GetObject("qrv13_0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv13_1 {
            get {
                object obj = ResourceManager.GetObject("qrv13_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv13_2 {
            get {
                object obj = ResourceManager.GetObject("qrv13_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv13_3 {
            get {
                object obj = ResourceManager.GetObject("qrv13_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv14_0 {
            get {
                object obj = ResourceManager.GetObject("qrv14_0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv14_1 {
            get {
                object obj = ResourceManager.GetObject("qrv14_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv14_2 {
            get {
                object obj = ResourceManager.GetObject("qrv14_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv14_3 {
            get {
                object obj = ResourceManager.GetObject("qrv14_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv15_0 {
            get {
                object obj = ResourceManager.GetObject("qrv15_0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv15_1 {
            get {
                object obj = ResourceManager.GetObject("qrv15_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv15_2 {
            get {
                object obj = ResourceManager.GetObject("qrv15_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv15_3 {
            get {
                object obj = ResourceManager.GetObject("qrv15_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv16_0 {
            get {
                object obj = ResourceManager.GetObject("qrv16_0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv16_1 {
            get {
                object obj = ResourceManager.GetObject("qrv16_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv16_2 {
            get {
                object obj = ResourceManager.GetObject("qrv16_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv16_3 {
            get {
                object obj = ResourceManager.GetObject("qrv16_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv17_0 {
            get {
                object obj = ResourceManager.GetObject("qrv17_0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv17_1 {
            get {
                object obj = ResourceManager.GetObject("qrv17_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv17_2 {
            get {
                object obj = ResourceManager.GetObject("qrv17_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv17_3 {
            get {
                object obj = ResourceManager.GetObject("qrv17_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv18_0 {
            get {
                object obj = ResourceManager.GetObject("qrv18_0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv18_1 {
            get {
                object obj = ResourceManager.GetObject("qrv18_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv18_2 {
            get {
                object obj = ResourceManager.GetObject("qrv18_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv18_3 {
            get {
                object obj = ResourceManager.GetObject("qrv18_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv19_0 {
            get {
                object obj = ResourceManager.GetObject("qrv19_0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv19_1 {
            get {
                object obj = ResourceManager.GetObject("qrv19_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv19_2 {
            get {
                object obj = ResourceManager.GetObject("qrv19_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv19_3 {
            get {
                object obj = ResourceManager.GetObject("qrv19_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv2_0 {
            get {
                object obj = ResourceManager.GetObject("qrv2_0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv2_1 {
            get {
                object obj = ResourceManager.GetObject("qrv2_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv2_2 {
            get {
                object obj = ResourceManager.GetObject("qrv2_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv2_3 {
            get {
                object obj = ResourceManager.GetObject("qrv2_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv20_0 {
            get {
                object obj = ResourceManager.GetObject("qrv20_0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv20_1 {
            get {
                object obj = ResourceManager.GetObject("qrv20_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv20_2 {
            get {
                object obj = ResourceManager.GetObject("qrv20_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv20_3 {
            get {
                object obj = ResourceManager.GetObject("qrv20_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv21_0 {
            get {
                object obj = ResourceManager.GetObject("qrv21_0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv21_1 {
            get {
                object obj = ResourceManager.GetObject("qrv21_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv21_2 {
            get {
                object obj = ResourceManager.GetObject("qrv21_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv21_3 {
            get {
                object obj = ResourceManager.GetObject("qrv21_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv22_0 {
            get {
                object obj = ResourceManager.GetObject("qrv22_0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv22_1 {
            get {
                object obj = ResourceManager.GetObject("qrv22_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv22_2 {
            get {
                object obj = ResourceManager.GetObject("qrv22_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv22_3 {
            get {
                object obj = ResourceManager.GetObject("qrv22_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv23_0 {
            get {
                object obj = ResourceManager.GetObject("qrv23_0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv23_1 {
            get {
                object obj = ResourceManager.GetObject("qrv23_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv23_2 {
            get {
                object obj = ResourceManager.GetObject("qrv23_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv23_3 {
            get {
                object obj = ResourceManager.GetObject("qrv23_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv24_0 {
            get {
                object obj = ResourceManager.GetObject("qrv24_0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv24_1 {
            get {
                object obj = ResourceManager.GetObject("qrv24_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv24_2 {
            get {
                object obj = ResourceManager.GetObject("qrv24_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv24_3 {
            get {
                object obj = ResourceManager.GetObject("qrv24_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv25_0 {
            get {
                object obj = ResourceManager.GetObject("qrv25_0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv25_1 {
            get {
                object obj = ResourceManager.GetObject("qrv25_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv25_2 {
            get {
                object obj = ResourceManager.GetObject("qrv25_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv25_3 {
            get {
                object obj = ResourceManager.GetObject("qrv25_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv26_0 {
            get {
                object obj = ResourceManager.GetObject("qrv26_0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv26_1 {
            get {
                object obj = ResourceManager.GetObject("qrv26_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv26_2 {
            get {
                object obj = ResourceManager.GetObject("qrv26_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv26_3 {
            get {
                object obj = ResourceManager.GetObject("qrv26_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv27_0 {
            get {
                object obj = ResourceManager.GetObject("qrv27_0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv27_1 {
            get {
                object obj = ResourceManager.GetObject("qrv27_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv27_2 {
            get {
                object obj = ResourceManager.GetObject("qrv27_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv27_3 {
            get {
                object obj = ResourceManager.GetObject("qrv27_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv28_0 {
            get {
                object obj = ResourceManager.GetObject("qrv28_0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv28_1 {
            get {
                object obj = ResourceManager.GetObject("qrv28_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv28_2 {
            get {
                object obj = ResourceManager.GetObject("qrv28_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv28_3 {
            get {
                object obj = ResourceManager.GetObject("qrv28_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv29_0 {
            get {
                object obj = ResourceManager.GetObject("qrv29_0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv29_1 {
            get {
                object obj = ResourceManager.GetObject("qrv29_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv29_2 {
            get {
                object obj = ResourceManager.GetObject("qrv29_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv29_3 {
            get {
                object obj = ResourceManager.GetObject("qrv29_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv3_0 {
            get {
                object obj = ResourceManager.GetObject("qrv3_0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv3_1 {
            get {
                object obj = ResourceManager.GetObject("qrv3_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv3_2 {
            get {
                object obj = ResourceManager.GetObject("qrv3_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv3_3 {
            get {
                object obj = ResourceManager.GetObject("qrv3_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv30_0 {
            get {
                object obj = ResourceManager.GetObject("qrv30_0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv30_1 {
            get {
                object obj = ResourceManager.GetObject("qrv30_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv30_2 {
            get {
                object obj = ResourceManager.GetObject("qrv30_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv30_3 {
            get {
                object obj = ResourceManager.GetObject("qrv30_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv31_0 {
            get {
                object obj = ResourceManager.GetObject("qrv31_0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv31_1 {
            get {
                object obj = ResourceManager.GetObject("qrv31_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv31_2 {
            get {
                object obj = ResourceManager.GetObject("qrv31_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv31_3 {
            get {
                object obj = ResourceManager.GetObject("qrv31_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv32_0 {
            get {
                object obj = ResourceManager.GetObject("qrv32_0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv32_1 {
            get {
                object obj = ResourceManager.GetObject("qrv32_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv32_2 {
            get {
                object obj = ResourceManager.GetObject("qrv32_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv32_3 {
            get {
                object obj = ResourceManager.GetObject("qrv32_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv33_0 {
            get {
                object obj = ResourceManager.GetObject("qrv33_0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv33_1 {
            get {
                object obj = ResourceManager.GetObject("qrv33_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv33_2 {
            get {
                object obj = ResourceManager.GetObject("qrv33_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv33_3 {
            get {
                object obj = ResourceManager.GetObject("qrv33_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv34_0 {
            get {
                object obj = ResourceManager.GetObject("qrv34_0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv34_1 {
            get {
                object obj = ResourceManager.GetObject("qrv34_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv34_2 {
            get {
                object obj = ResourceManager.GetObject("qrv34_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv34_3 {
            get {
                object obj = ResourceManager.GetObject("qrv34_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv35_0 {
            get {
                object obj = ResourceManager.GetObject("qrv35_0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv35_1 {
            get {
                object obj = ResourceManager.GetObject("qrv35_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv35_2 {
            get {
                object obj = ResourceManager.GetObject("qrv35_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv35_3 {
            get {
                object obj = ResourceManager.GetObject("qrv35_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv36_0 {
            get {
                object obj = ResourceManager.GetObject("qrv36_0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv36_1 {
            get {
                object obj = ResourceManager.GetObject("qrv36_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv36_2 {
            get {
                object obj = ResourceManager.GetObject("qrv36_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv36_3 {
            get {
                object obj = ResourceManager.GetObject("qrv36_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv37_0 {
            get {
                object obj = ResourceManager.GetObject("qrv37_0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv37_1 {
            get {
                object obj = ResourceManager.GetObject("qrv37_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv37_2 {
            get {
                object obj = ResourceManager.GetObject("qrv37_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv37_3 {
            get {
                object obj = ResourceManager.GetObject("qrv37_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv38_0 {
            get {
                object obj = ResourceManager.GetObject("qrv38_0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv38_1 {
            get {
                object obj = ResourceManager.GetObject("qrv38_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv38_2 {
            get {
                object obj = ResourceManager.GetObject("qrv38_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv38_3 {
            get {
                object obj = ResourceManager.GetObject("qrv38_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv39_0 {
            get {
                object obj = ResourceManager.GetObject("qrv39_0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv39_1 {
            get {
                object obj = ResourceManager.GetObject("qrv39_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv39_2 {
            get {
                object obj = ResourceManager.GetObject("qrv39_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv39_3 {
            get {
                object obj = ResourceManager.GetObject("qrv39_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv4_0 {
            get {
                object obj = ResourceManager.GetObject("qrv4_0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv4_1 {
            get {
                object obj = ResourceManager.GetObject("qrv4_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv4_2 {
            get {
                object obj = ResourceManager.GetObject("qrv4_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv4_3 {
            get {
                object obj = ResourceManager.GetObject("qrv4_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv40_0 {
            get {
                object obj = ResourceManager.GetObject("qrv40_0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv40_1 {
            get {
                object obj = ResourceManager.GetObject("qrv40_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv40_2 {
            get {
                object obj = ResourceManager.GetObject("qrv40_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv40_3 {
            get {
                object obj = ResourceManager.GetObject("qrv40_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv5_0 {
            get {
                object obj = ResourceManager.GetObject("qrv5_0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv5_1 {
            get {
                object obj = ResourceManager.GetObject("qrv5_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv5_2 {
            get {
                object obj = ResourceManager.GetObject("qrv5_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv5_3 {
            get {
                object obj = ResourceManager.GetObject("qrv5_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv6_0 {
            get {
                object obj = ResourceManager.GetObject("qrv6_0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv6_1 {
            get {
                object obj = ResourceManager.GetObject("qrv6_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv6_2 {
            get {
                object obj = ResourceManager.GetObject("qrv6_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv6_3 {
            get {
                object obj = ResourceManager.GetObject("qrv6_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv7_0 {
            get {
                object obj = ResourceManager.GetObject("qrv7_0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv7_1 {
            get {
                object obj = ResourceManager.GetObject("qrv7_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv7_2 {
            get {
                object obj = ResourceManager.GetObject("qrv7_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv7_3 {
            get {
                object obj = ResourceManager.GetObject("qrv7_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv8_0 {
            get {
                object obj = ResourceManager.GetObject("qrv8_0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv8_1 {
            get {
                object obj = ResourceManager.GetObject("qrv8_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv8_2 {
            get {
                object obj = ResourceManager.GetObject("qrv8_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv8_3 {
            get {
                object obj = ResourceManager.GetObject("qrv8_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv9_0 {
            get {
                object obj = ResourceManager.GetObject("qrv9_0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv9_1 {
            get {
                object obj = ResourceManager.GetObject("qrv9_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv9_2 {
            get {
                object obj = ResourceManager.GetObject("qrv9_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrv9_3 {
            get {
                object obj = ResourceManager.GetObject("qrv9_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrvfr1 {
            get {
                object obj = ResourceManager.GetObject("qrvfr1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrvfr10 {
            get {
                object obj = ResourceManager.GetObject("qrvfr10", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrvfr11 {
            get {
                object obj = ResourceManager.GetObject("qrvfr11", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrvfr12 {
            get {
                object obj = ResourceManager.GetObject("qrvfr12", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrvfr13 {
            get {
                object obj = ResourceManager.GetObject("qrvfr13", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrvfr14 {
            get {
                object obj = ResourceManager.GetObject("qrvfr14", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrvfr15 {
            get {
                object obj = ResourceManager.GetObject("qrvfr15", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrvfr16 {
            get {
                object obj = ResourceManager.GetObject("qrvfr16", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrvfr17 {
            get {
                object obj = ResourceManager.GetObject("qrvfr17", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrvfr18 {
            get {
                object obj = ResourceManager.GetObject("qrvfr18", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrvfr19 {
            get {
                object obj = ResourceManager.GetObject("qrvfr19", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrvfr2 {
            get {
                object obj = ResourceManager.GetObject("qrvfr2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrvfr20 {
            get {
                object obj = ResourceManager.GetObject("qrvfr20", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrvfr21 {
            get {
                object obj = ResourceManager.GetObject("qrvfr21", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrvfr22 {
            get {
                object obj = ResourceManager.GetObject("qrvfr22", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrvfr23 {
            get {
                object obj = ResourceManager.GetObject("qrvfr23", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrvfr24 {
            get {
                object obj = ResourceManager.GetObject("qrvfr24", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrvfr25 {
            get {
                object obj = ResourceManager.GetObject("qrvfr25", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrvfr26 {
            get {
                object obj = ResourceManager.GetObject("qrvfr26", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrvfr27 {
            get {
                object obj = ResourceManager.GetObject("qrvfr27", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrvfr28 {
            get {
                object obj = ResourceManager.GetObject("qrvfr28", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrvfr29 {
            get {
                object obj = ResourceManager.GetObject("qrvfr29", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrvfr3 {
            get {
                object obj = ResourceManager.GetObject("qrvfr3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrvfr30 {
            get {
                object obj = ResourceManager.GetObject("qrvfr30", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrvfr31 {
            get {
                object obj = ResourceManager.GetObject("qrvfr31", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrvfr32 {
            get {
                object obj = ResourceManager.GetObject("qrvfr32", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrvfr33 {
            get {
                object obj = ResourceManager.GetObject("qrvfr33", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrvfr34 {
            get {
                object obj = ResourceManager.GetObject("qrvfr34", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrvfr35 {
            get {
                object obj = ResourceManager.GetObject("qrvfr35", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrvfr36 {
            get {
                object obj = ResourceManager.GetObject("qrvfr36", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrvfr37 {
            get {
                object obj = ResourceManager.GetObject("qrvfr37", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrvfr38 {
            get {
                object obj = ResourceManager.GetObject("qrvfr38", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrvfr39 {
            get {
                object obj = ResourceManager.GetObject("qrvfr39", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrvfr4 {
            get {
                object obj = ResourceManager.GetObject("qrvfr4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrvfr40 {
            get {
                object obj = ResourceManager.GetObject("qrvfr40", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrvfr5 {
            get {
                object obj = ResourceManager.GetObject("qrvfr5", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrvfr6 {
            get {
                object obj = ResourceManager.GetObject("qrvfr6", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrvfr7 {
            get {
                object obj = ResourceManager.GetObject("qrvfr7", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrvfr8 {
            get {
                object obj = ResourceManager.GetObject("qrvfr8", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] qrvfr9 {
            get {
                object obj = ResourceManager.GetObject("qrvfr9", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] rsc10 {
            get {
                object obj = ResourceManager.GetObject("rsc10", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] rsc13 {
            get {
                object obj = ResourceManager.GetObject("rsc13", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] rsc15 {
            get {
                object obj = ResourceManager.GetObject("rsc15", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] rsc16 {
            get {
                object obj = ResourceManager.GetObject("rsc16", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] rsc17 {
            get {
                object obj = ResourceManager.GetObject("rsc17", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] rsc18 {
            get {
                object obj = ResourceManager.GetObject("rsc18", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] rsc20 {
            get {
                object obj = ResourceManager.GetObject("rsc20", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] rsc22 {
            get {
                object obj = ResourceManager.GetObject("rsc22", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] rsc24 {
            get {
                object obj = ResourceManager.GetObject("rsc24", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] rsc26 {
            get {
                object obj = ResourceManager.GetObject("rsc26", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] rsc28 {
            get {
                object obj = ResourceManager.GetObject("rsc28", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] rsc30 {
            get {
                object obj = ResourceManager.GetObject("rsc30", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] rsc32 {
            get {
                object obj = ResourceManager.GetObject("rsc32", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] rsc34 {
            get {
                object obj = ResourceManager.GetObject("rsc34", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] rsc36 {
            get {
                object obj = ResourceManager.GetObject("rsc36", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] rsc40 {
            get {
                object obj = ResourceManager.GetObject("rsc40", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] rsc42 {
            get {
                object obj = ResourceManager.GetObject("rsc42", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] rsc44 {
            get {
                object obj = ResourceManager.GetObject("rsc44", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] rsc46 {
            get {
                object obj = ResourceManager.GetObject("rsc46", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] rsc48 {
            get {
                object obj = ResourceManager.GetObject("rsc48", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] rsc50 {
            get {
                object obj = ResourceManager.GetObject("rsc50", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] rsc52 {
            get {
                object obj = ResourceManager.GetObject("rsc52", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] rsc54 {
            get {
                object obj = ResourceManager.GetObject("rsc54", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] rsc56 {
            get {
                object obj = ResourceManager.GetObject("rsc56", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] rsc58 {
            get {
                object obj = ResourceManager.GetObject("rsc58", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] rsc60 {
            get {
                object obj = ResourceManager.GetObject("rsc60", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] rsc62 {
            get {
                object obj = ResourceManager.GetObject("rsc62", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] rsc64 {
            get {
                object obj = ResourceManager.GetObject("rsc64", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] rsc66 {
            get {
                object obj = ResourceManager.GetObject("rsc66", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] rsc68 {
            get {
                object obj = ResourceManager.GetObject("rsc68", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] rsc7 {
            get {
                object obj = ResourceManager.GetObject("rsc7", resourceCulture);
                return ((byte[])(obj));
            }
        }

        internal static byte[] GetResource(String name)
        {
            object obj = ResourceManager.GetObject(name, resourceCulture);
            return ((byte[])(obj));

        }
    }
}
